import type { Locale } from '@luminol/localization';

const ar = {
  title: 'مركز قيادة الأكاديمية',
  subtitle: 'من الفكرة إلى الخطوة التالية، بإشرافك.',
  home: 'إدارة الأكاديمية',
  approvals: 'مركز الموافقات',
  knowledge: 'ذاكرة الأكاديمية',
  tasks: 'الأهداف والمهام',
  activity: 'سجل النشاط',
  connectors: 'الاتصالات',
  conversation: 'تحدث مع لومينول',
  prompt: 'كيف يمكنني مساعدتك اليوم؟',
  submit: 'ابدأ',
  pending: 'جارٍ العمل…',
  error: 'تعذر إكمال الطلب. تحقق من الإدخال والاتصال ثم حاول مجدداً.',
  local: 'مساعد محلي موجّه · دون تكلفة نماذج',
  safety: 'كل إرسال أو نشر أو تعديل سجل يتطلب موافقة صريحة.',
  empty: 'لا توجد بيانات بعد.',
  leads: 'طلبات تستحق الانتباه',
  score: 'درجة انتباه تشغيلية',
  reasons: 'أسباب الأولوية',
  overdue: 'متابعة متأخرة',
  unassigned: 'دون مسؤول',
  waiting: 'انتظار ٤٨ ساعة أو أكثر',
  leadScope:
    'أعلى ٢٠ طلباً من أحدث ٢٠٠ طلب نشط. الدرجة ليست توقعاً للدفع أو حكماً على الشخص.',
  draft: 'مسودة متابعة',
  draftText:
    'مرحباً، شكراً لتواصلك مع أكاديمية لومينول. هل ترغب في الحصول على تفاصيل البرنامج وخطوات التسجيل؟ يسعد فريقنا مساعدتك.',
  draftApprove: 'اطلب الموافقة على هذه الرسالة',
  planApprove: 'اطلب الموافقة على خطة المتابعة',
  nextAction: 'الخطوة التالية',
  due: 'التاريخ',
  nextDefault: 'راجع الطلب وحضّر متابعة للمراجعة',
  titleLabel: 'العنوان',
  goal: 'الهدف',
  agent: 'الوكيل المسؤول',
  saveTask: 'أضف مهمة',
  complete: 'تم الإنجاز',
  source: 'المصدر الموثوق',
  content: 'المعرفة المعتمدة',
  approveKnowledge: 'اعتمد وأضف إلى الذاكرة',
  archive: 'أوقف استخدام المرجع',
  knowledgeNote:
    'اعتمادك يؤكد صحة المصدر. تُعرض النصوص المطابقة كما هي دون اختراع معلومات. احتفظ بتفاصيل العملاء في CRM.',
  notifications: 'يحتاج إلى انتباه',
  dueTasks: 'مهام مستحقة',
  approvalCount: 'بانتظار الموافقة',
  all: 'المزيد',
  connected: 'متاح',
  needsCredentials: 'يحتاج إعداداً',
  manual: 'يدوي بعد الموافقة',
  readOnly: 'قراءة وصياغة',
  activityNote:
    'سجل شخصي دائم. قرارات الموافقة والتنفيذ محفوظة في مركز الموافقات.',
  handoff: 'افتح WhatsApp يدوياً',
  handoffNote:
    'فتح الرابط لا يثبت الإرسال. راجع داخل WhatsApp واضغط إرسال بنفسك.',
  intentions: {
    briefing: 'ملخص اليوم',
    triage: 'فرز الطلبات',
    'follow-up': 'حضّر المتابعة',
    faq: 'سؤال عن الدورات',
    plan: 'خطط للمهام',
    revenue: 'ملخص الإيرادات',
    content: 'تقويم ومحتوى',
    booking: 'الحجز والاستشارات',
    social: 'أداء المنصات',
  },
  agents: {
    main: 'لومينول · المنسّق',
    leads: 'العملاء المحتملون',
    booking: 'الحجز',
    courses: 'الدورات',
    revenue: 'الإيرادات',
    content: 'المحتوى',
    fettouma: 'معرفة فتومة',
  },
  events: {
    COMMAND_COMPLETED: 'اكتمل الطلب',
    KNOWLEDGE_APPROVED: 'اعتُمد مرجع',
    KNOWLEDGE_ARCHIVED: 'أُوقف مرجع',
    TASK_CREATED: 'أُضيفت مهمة',
    TASK_COMPLETED: 'أُنجزت مهمة',
    MANUAL_HANDOFF_OPENED_NOT_SENT: 'فُتح رابط WhatsApp، دون تأكيد إرسال',
  },
};
type MuseCopy = {
  [K in keyof typeof ar]: (typeof ar)[K] extends string
    ? string
    : { [P in keyof (typeof ar)[K]]: string };
};
const fr: MuseCopy = {
  title: 'Le centre de commande de l’académie',
  subtitle: 'De l’idée à la prochaine étape, sous votre contrôle.',
  home: 'Administration',
  approvals: 'Approbations',
  knowledge: 'Mémoire de l’académie',
  tasks: 'Objectifs et tâches',
  activity: 'Journal d’activité',
  connectors: 'Connexions',
  conversation: 'Parler à Luminol',
  prompt: 'Comment puis-je vous aider aujourd’hui ?',
  submit: 'Lancer',
  pending: 'En cours…',
  error:
    'Impossible de terminer. Vérifiez la saisie et la connexion, puis réessayez.',
  local: 'Assistant local guidé · sans coût de modèle',
  safety:
    'Chaque envoi, publication ou modification nécessite une approbation explicite.',
  empty: 'Aucune donnée pour le moment.',
  leads: 'Demandes à examiner',
  score: 'Score d’attention opérationnelle',
  reasons: 'Motifs',
  overdue: 'Relance en retard',
  unassigned: 'Sans responsable',
  waiting: 'Attente de 48 h ou plus',
  leadScope:
    'Top 20 parmi les 200 dernières demandes actives. Ce score ne prédit pas le paiement et ne juge pas une personne.',
  draft: 'Brouillon de relance',
  draftText:
    'Bonjour, merci de votre intérêt pour Luminol Academy. Souhaitez-vous recevoir les détails du programme et les étapes d’inscription ? Notre équipe sera ravie de vous aider.',
  draftApprove: 'Demander l’approbation du message',
  planApprove: 'Demander l’approbation du plan',
  nextAction: 'Prochaine action',
  due: 'Date',
  nextDefault: 'Revoir la demande et préparer une relance pour validation',
  titleLabel: 'Titre',
  goal: 'Objectif',
  agent: 'Agent responsable',
  saveTask: 'Ajouter une tâche',
  complete: 'Terminer',
  source: 'Source vérifiée',
  content: 'Connaissance approuvée',
  approveKnowledge: 'Approuver et mémoriser',
  archive: 'Retirer la source',
  knowledgeNote:
    'Votre approbation confirme la source. Les extraits correspondants sont cités sans invention. Conservez les données clients dans le CRM.',
  notifications: 'À examiner',
  dueTasks: 'Tâches échues',
  approvalCount: 'En attente d’approbation',
  all: 'Voir plus',
  connected: 'Disponible',
  needsCredentials: 'Configuration requise',
  manual: 'Manuel après approbation',
  readOnly: 'Lecture et brouillons',
  activityNote:
    'Journal personnel persistant. Les décisions et exécutions figurent dans le centre d’approbation.',
  handoff: 'Ouvrir WhatsApp manuellement',
  handoffNote:
    'Ouvrir le lien ne confirme pas l’envoi. Vérifiez et envoyez vous-même dans WhatsApp.',
  intentions: {
    briefing: 'Briefing du jour',
    triage: 'Trier les demandes',
    'follow-up': 'Préparer les relances',
    faq: 'FAQ des formations',
    plan: 'Planifier les tâches',
    revenue: 'Résumé financier',
    content: 'Calendrier et légendes',
    booking: 'Rendez-vous',
    social: 'Performances sociales',
  },
  agents: {
    main: 'Luminol · Coordinateur',
    leads: 'Prospects',
    booking: 'Rendez-vous',
    courses: 'Formations',
    revenue: 'Revenus',
    content: 'Contenu',
    fettouma: 'Savoir de Fettouma',
  },
  events: {
    COMMAND_COMPLETED: 'Commande terminée',
    KNOWLEDGE_APPROVED: 'Source approuvée',
    KNOWLEDGE_ARCHIVED: 'Source retirée',
    TASK_CREATED: 'Tâche ajoutée',
    TASK_COMPLETED: 'Tâche terminée',
    MANUAL_HANDOFF_OPENED_NOT_SENT: 'WhatsApp ouvert, envoi non confirmé',
  },
};
const en: MuseCopy = {
  title: 'Your academy command center',
  subtitle: 'From an idea to the next step, with you in control.',
  home: 'Academy admin',
  approvals: 'Approval center',
  knowledge: 'Academy memory',
  tasks: 'Goals & tasks',
  activity: 'Activity trail',
  connectors: 'Connections',
  conversation: 'Talk to Luminol',
  prompt: 'What can I help you move forward today?',
  submit: 'Run',
  pending: 'Working…',
  error:
    'Could not complete the request. Check your input and connection, then retry.',
  local: 'Guided local assistant · no model spend',
  safety:
    'Every send, publication or record change requires explicit approval.',
  empty: 'No data yet.',
  leads: 'Enquiries needing attention',
  score: 'Operational attention score',
  reasons: 'Priority reasons',
  overdue: 'Overdue follow-up',
  unassigned: 'No owner',
  waiting: 'Waiting 48 h or more',
  leadScope:
    'Top 20 of the 200 most recent active enquiries. Scores do not predict payment or judge a person.',
  draft: 'Follow-up draft',
  draftText:
    'Hello, thank you for your interest in Luminol Academy. Would you like the programme details and registration steps? Our team would be happy to help.',
  draftApprove: 'Request approval for this message',
  planApprove: 'Request approval for this follow-up plan',
  nextAction: 'Next action',
  due: 'Date',
  nextDefault: 'Review enquiry and prepare a follow-up for review',
  titleLabel: 'Title',
  goal: 'Goal',
  agent: 'Responsible agent',
  saveTask: 'Add task',
  complete: 'Complete',
  source: 'Verified source',
  content: 'Approved knowledge',
  approveKnowledge: 'Approve & add to memory',
  archive: 'Retire source',
  knowledgeNote:
    'Your approval confirms the source. Matching excerpts are quoted without invention. Keep customer details in CRM.',
  notifications: 'Needs your attention',
  dueTasks: 'Tasks due',
  approvalCount: 'Awaiting approval',
  all: 'View more',
  connected: 'Available',
  needsCredentials: 'Setup needed',
  manual: 'Manual after approval',
  readOnly: 'Read & draft',
  activityNote:
    'Persistent personal activity trail. Approval decisions and executions live in the approval center.',
  handoff: 'Open WhatsApp manually',
  handoffNote:
    'Opening the link does not confirm sending. Review and press send yourself in WhatsApp.',
  intentions: {
    briefing: 'Daily briefing',
    triage: 'Triage leads',
    'follow-up': 'Draft follow-ups',
    faq: 'Course FAQ',
    plan: 'Plan my tasks',
    revenue: 'Revenue summary',
    content: 'Calendar & captions',
    booking: 'Bookings',
    social: 'Social performance',
  },
  agents: {
    main: 'Luminol · Coordinator',
    leads: 'Leads',
    booking: 'Booking',
    courses: 'Courses',
    revenue: 'Revenue',
    content: 'Content',
    fettouma: 'Fettouma Knowledge',
  },
  events: {
    COMMAND_COMPLETED: 'Command completed',
    KNOWLEDGE_APPROVED: 'Source approved',
    KNOWLEDGE_ARCHIVED: 'Source retired',
    TASK_CREATED: 'Task added',
    TASK_COMPLETED: 'Task completed',
    MANUAL_HANDOFF_OPENED_NOT_SENT: 'WhatsApp opened, sending unconfirmed',
  },
};
export function getMuseCopy(locale: Locale): MuseCopy {
  return { ar, fr, en }[locale];
}
